from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class PhotoshopSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class Photoshop(PhotoshopSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def documents(self) -> list[DocumentProxy]: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_layer(self) -> LayerProxy | None: ...
    @property
    def activeLayer(self) -> LayerProxy | None: ...
    @property
    def active_layers(self) -> list[LayerProxy]: ...
    @property
    def activeLayers(self) -> list[LayerProxy]: ...
    @property
    def selection(self) -> SelectionProxy | None: ...
    @property
    def channels(self) -> list[ChannelProxy]: ...
    @property
    def active_text(self) -> TextItemProxy | None: ...
    @property
    def activeText(self) -> TextItemProxy | None: ...
    def batch_play(self, descriptors: list[dict[str, Any]], options: dict[str, Any] | None = ..., **kwargs: Any) -> Any: ...
    def batchPlay(self, descriptors: list[dict[str, Any]], options: dict[str, Any] | None = ..., **kwargs: Any) -> Any: ...


class PhotoshopApp:
    @property
    def version(self) -> str: ...
    @property
    def documents(self) -> list[DocumentProxy]: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_layer(self) -> LayerProxy | None: ...
    @property
    def activeLayer(self) -> LayerProxy | None: ...
    @property
    def active_layers(self) -> list[LayerProxy]: ...
    @property
    def activeLayers(self) -> list[LayerProxy]: ...
    @property
    def selection(self) -> SelectionProxy | None: ...
    @property
    def channels(self) -> list[ChannelProxy]: ...
    @property
    def active_text(self) -> TextItemProxy | None: ...
    @property
    def activeText(self) -> TextItemProxy | None: ...


class PhotoshopAction:
    def batch_play(self, *args: Any, **kwargs: Any) -> Any: ...
    def batchPlay(self, *args: Any, **kwargs: Any) -> Any: ...


class DocumentProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def resolution(self) -> Any: ...
    @property
    def saved(self) -> bool | None: ...
    @property
    def mode(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def active_layers(self) -> list[LayerProxy]: ...
    @property
    def activeLayers(self) -> list[LayerProxy]: ...
    @property
    def selection(self) -> SelectionProxy: ...
    @property
    def channels(self) -> list[ChannelProxy]: ...
    @property
    def active_channels(self) -> list[ChannelProxy]: ...
    @property
    def activeChannels(self) -> list[ChannelProxy]: ...
    @property
    def component_channels(self) -> list[ChannelProxy]: ...
    @property
    def componentChannels(self) -> list[ChannelProxy]: ...
    @property
    def dom(self) -> PhotoshopDomProxy: ...
    def refresh(self, *args: Any, **kwargs: Any) -> DocumentProxy: ...
    def get_channel(self, *args: Any, **kwargs: Any) -> ChannelProxy | None: ...
    def getChannel(self, *args: Any, **kwargs: Any) -> ChannelProxy | None: ...
    def save_as(self, *args: Any, **kwargs: Any) -> Any: ...
    def saveAs(self, *args: Any, **kwargs: Any) -> Any: ...
    def export(self, *args: Any, **kwargs: Any) -> Any: ...


class LayerProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def kind(self) -> str | None: ...
    @property
    def opacity(self) -> Any: ...
    @property
    def visible(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def has_children(self) -> bool: ...
    @property
    def hasChildren(self) -> bool: ...
    @property
    def text_item(self) -> TextItemProxy | None: ...
    @property
    def textItem(self) -> TextItemProxy | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    def hide(self, *args: Any, **kwargs: Any) -> Any: ...


class SelectionProxy:
    @property
    def bounds(self) -> dict[str, Any] | None: ...
    @property
    def doc_id(self) -> int | str | None: ...
    @property
    def docId(self) -> int | str | None: ...
    @property
    def solid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def refresh(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def select_all(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def selectAll(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def deselect(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def inverse(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def select_rectangle(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def selectRectangle(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def select_ellipse(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def selectEllipse(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def select_polygon(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def selectPolygon(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def select_row(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def selectRow(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def select_column(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def selectColumn(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def expand(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def contract(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def feather(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def smooth(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def grow(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def translate_boundary(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def translateBoundary(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...
    def save(self, *args: Any, **kwargs: Any) -> SelectionProxy: ...


class ChannelProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def kind(self) -> str | None: ...
    @property
    def opacity(self) -> Any: ...
    @property
    def visible(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def remove(self, *args: Any, **kwargs: Any) -> ChannelProxy: ...


class TextItemProxy:
    @property
    def layer_id(self) -> int | str | None: ...
    @property
    def layerId(self) -> int | str | None: ...
    @property
    def contents(self) -> str | None: ...
    @property
    def is_paragraph_text(self) -> bool | None: ...
    @property
    def isParagraphText(self) -> bool | None: ...
    @property
    def is_point_text(self) -> bool | None: ...
    @property
    def isPointText(self) -> bool | None: ...
    @property
    def orientation(self) -> str | None: ...
    @property
    def text_click_point(self) -> dict[str, Any] | None: ...
    @property
    def textClickPoint(self) -> dict[str, Any] | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def character_style(self) -> CharacterStyleProxy: ...
    @property
    def characterStyle(self) -> CharacterStyleProxy: ...
    @property
    def paragraph_style(self) -> ParagraphStyleProxy: ...
    @property
    def paragraphStyle(self) -> ParagraphStyleProxy: ...
    def refresh(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def set_contents(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def setContents(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def set_character_style(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def setCharacterStyle(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def set_paragraph_style(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def setParagraphStyle(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def set_text_click_point(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def setTextClickPoint(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def set_orientation(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def setOrientation(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def convert_to_paragraph_text(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def convertToParagraphText(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def convert_to_point_text(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def convertToPointText(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def convert_to_shape(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def convertToShape(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def create_work_path(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def createWorkPath(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...


class CharacterStyleProxy:
    def update(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...
    def reset(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...


class ParagraphStyleProxy:
    def update(self, *args: Any, **kwargs: Any) -> TextItemProxy: ...


class PhotoshopDomProxy:
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def call(self, *args: Any, **kwargs: Any) -> Any: ...
