from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class PhotoshopSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class Photoshop(PhotoshopSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def documents(self) -> list[DocumentProxy]: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_layer(self) -> LayerProxy | None: ...
    @property
    def activeLayer(self) -> LayerProxy | None: ...
    @property
    def active_layers(self) -> list[LayerProxy]: ...
    @property
    def activeLayers(self) -> list[LayerProxy]: ...
    def batch_play(self, descriptors: list[dict[str, Any]], options: dict[str, Any] | None = ..., **kwargs: Any) -> Any: ...
    def batchPlay(self, descriptors: list[dict[str, Any]], options: dict[str, Any] | None = ..., **kwargs: Any) -> Any: ...


class PhotoshopApp:
    @property
    def version(self) -> str: ...
    @property
    def documents(self) -> list[DocumentProxy]: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_layer(self) -> LayerProxy | None: ...
    @property
    def activeLayer(self) -> LayerProxy | None: ...
    @property
    def active_layers(self) -> list[LayerProxy]: ...
    @property
    def activeLayers(self) -> list[LayerProxy]: ...


class PhotoshopAction:
    def batch_play(self, *args: Any, **kwargs: Any) -> Any: ...
    def batchPlay(self, *args: Any, **kwargs: Any) -> Any: ...


class DocumentProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def resolution(self) -> Any: ...
    @property
    def saved(self) -> bool | None: ...
    @property
    def mode(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def active_layers(self) -> list[LayerProxy]: ...
    @property
    def activeLayers(self) -> list[LayerProxy]: ...
    @property
    def dom(self) -> PhotoshopDomProxy: ...
    def refresh(self, *args: Any, **kwargs: Any) -> DocumentProxy: ...
    def save_as(self, *args: Any, **kwargs: Any) -> Any: ...
    def saveAs(self, *args: Any, **kwargs: Any) -> Any: ...
    def export(self, *args: Any, **kwargs: Any) -> Any: ...


class LayerProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def kind(self) -> str | None: ...
    @property
    def opacity(self) -> Any: ...
    @property
    def visible(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def has_children(self) -> bool: ...
    @property
    def hasChildren(self) -> bool: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    def hide(self, *args: Any, **kwargs: Any) -> Any: ...


class PhotoshopDomProxy:
    def get(self, *args: Any, **kwargs: Any) -> Any: ...
    def call(self, *args: Any, **kwargs: Any) -> Any: ...
