from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class AfterEffectsSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class AfterEffects(AfterEffectsSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_project(self) -> ProjectProxy | None: ...
    @property
    def activeProject(self) -> ProjectProxy | None: ...
    @property
    def active_item(self) -> ProjectItemProxy | None: ...
    @property
    def activeItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...


class AfterEffectsApp:
    @property
    def version(self) -> str: ...
    @property
    def active_project(self) -> ProjectProxy | None: ...
    @property
    def activeProject(self) -> ProjectProxy | None: ...
    @property
    def active_item(self) -> ProjectItemProxy | None: ...
    @property
    def activeItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...


class ProjectProxy:
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def itemCount(self) -> int | None: ...
    @property
    def items(self) -> list[ProjectItemProxy]: ...
    @property
    def compositions(self) -> list[CompositionProxy]: ...
    @property
    def footage_items(self) -> list[FootageItemProxy]: ...
    @property
    def footageItems(self) -> list[FootageItemProxy]: ...
    @property
    def folders(self) -> list[FolderItemProxy]: ...
    @property
    def active_item(self) -> ProjectItemProxy | None: ...
    @property
    def activeItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...
    @property
    def render_queue(self) -> RenderQueueProxy: ...
    @property
    def renderQueue(self) -> RenderQueueProxy: ...
    def get_item_by_id(self, *args: Any, **kwargs: Any) -> ProjectItemProxy | None: ...
    def getItemById(self, *args: Any, **kwargs: Any) -> ProjectItemProxy | None: ...
    def get_items_by_name(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...
    def getItemsByName(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...


class ProjectItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def frame_rate(self) -> float | None: ...
    @property
    def frameRate(self) -> float | None: ...
    @property
    def has_video(self) -> bool | None: ...
    @property
    def hasVideo(self) -> bool | None: ...
    @property
    def has_audio(self) -> bool | None: ...
    @property
    def hasAudio(self) -> bool | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def missing_footage(self) -> bool | None: ...
    @property
    def missingFootage(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class CompositionProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def frame_rate(self) -> float | None: ...
    @property
    def frameRate(self) -> float | None: ...
    @property
    def num_layers(self) -> int | None: ...
    @property
    def numLayers(self) -> int | None: ...
    @property
    def work_area_start(self) -> float | None: ...
    @property
    def workAreaStart(self) -> float | None: ...
    @property
    def work_area_duration(self) -> float | None: ...
    @property
    def workAreaDuration(self) -> float | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def selected_layers(self) -> list[LayerProxy]: ...
    @property
    def selectedLayers(self) -> list[LayerProxy]: ...
    @property
    def typename(self) -> str | None: ...
    def get_layer_by_id(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def getLayerById(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def add_to_render_queue(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def addToRenderQueue(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...


class FootageItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def duration(self) -> float | None: ...
    @property
    def frame_rate(self) -> float | None: ...
    @property
    def frameRate(self) -> float | None: ...
    @property
    def has_video(self) -> bool | None: ...
    @property
    def hasVideo(self) -> bool | None: ...
    @property
    def has_audio(self) -> bool | None: ...
    @property
    def hasAudio(self) -> bool | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def missing_footage(self) -> bool | None: ...
    @property
    def missingFootage(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class FolderItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def parent_folder_id(self) -> Any: ...
    @property
    def parentFolderId(self) -> Any: ...
    @property
    def parent_folder_name(self) -> str | None: ...
    @property
    def parentFolderName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def is_active(self) -> bool | None: ...
    @property
    def isActive(self) -> bool | None: ...
    @property
    def item_count(self) -> int | None: ...
    @property
    def itemCount(self) -> int | None: ...
    @property
    def typename(self) -> str | None: ...


class LayerProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type_name(self) -> str | None: ...
    @property
    def typeName(self) -> str | None: ...
    @property
    def layer_type(self) -> str | None: ...
    @property
    def layerType(self) -> str | None: ...
    @property
    def comp_id(self) -> Any: ...
    @property
    def compId(self) -> Any: ...
    @property
    def source_id(self) -> Any: ...
    @property
    def sourceId(self) -> Any: ...
    @property
    def source_name(self) -> str | None: ...
    @property
    def sourceName(self) -> str | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def enabled(self) -> bool | None: ...
    @property
    def solo(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def shy(self) -> bool | None: ...
    @property
    def is_text(self) -> bool | None: ...
    @property
    def isText(self) -> bool | None: ...
    @property
    def start_time(self) -> float | None: ...
    @property
    def startTime(self) -> float | None: ...
    @property
    def in_point(self) -> float | None: ...
    @property
    def inPoint(self) -> float | None: ...
    @property
    def out_point(self) -> float | None: ...
    @property
    def outPoint(self) -> float | None: ...
    @property
    def stretch(self) -> float | None: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def has_video(self) -> bool | None: ...
    @property
    def hasVideo(self) -> bool | None: ...
    @property
    def has_audio(self) -> bool | None: ...
    @property
    def hasAudio(self) -> bool | None: ...
    @property
    def effects(self) -> list[EffectProxy]: ...
    @property
    def masks(self) -> list[MaskProxy]: ...
    @property
    def source_text(self) -> SourceTextProxy | None: ...
    @property
    def sourceText(self) -> SourceTextProxy | None: ...
    @property
    def typename(self) -> str | None: ...
    def get_effect(self, *args: Any, **kwargs: Any) -> EffectProxy | None: ...
    def getEffect(self, *args: Any, **kwargs: Any) -> EffectProxy | None: ...
    def set_source_text(self, *args: Any, **kwargs: Any) -> SourceTextProxy: ...
    def setSourceText(self, *args: Any, **kwargs: Any) -> SourceTextProxy: ...


class MaskProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def mask_mode(self) -> str | None: ...
    @property
    def maskMode(self) -> str | None: ...
    @property
    def inverted(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def roto_bezier(self) -> bool | None: ...
    @property
    def rotoBezier(self) -> bool | None: ...
    @property
    def opacity(self) -> Any: ...
    @property
    def feather(self) -> Any: ...
    @property
    def expansion(self) -> Any: ...
    @property
    def typename(self) -> str | None: ...


class EffectProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def match_name(self) -> str | None: ...
    @property
    def matchName(self) -> str | None: ...
    @property
    def enabled(self) -> bool | None: ...
    @property
    def active(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def property_count(self) -> int | None: ...
    @property
    def propertyCount(self) -> int | None: ...
    @property
    def typename(self) -> str | None: ...


class SourceTextProxy:
    @property
    def text(self) -> str | None: ...
    @property
    def font(self) -> str | None: ...
    @property
    def font_size(self) -> float | None: ...
    @property
    def fontSize(self) -> float | None: ...
    @property
    def fill_color(self) -> Any: ...
    @property
    def fillColor(self) -> Any: ...
    @property
    def stroke_color(self) -> Any: ...
    @property
    def strokeColor(self) -> Any: ...
    @property
    def tracking(self) -> Any: ...
    @property
    def justification(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...


class RenderQueueProxy:
    @property
    def num_items(self) -> int | None: ...
    @property
    def numItems(self) -> int | None: ...
    @property
    def can_queue_in_ame(self) -> bool | None: ...
    @property
    def canQueueInAme(self) -> bool | None: ...
    @property
    def queue_notify(self) -> bool | None: ...
    @property
    def queueNotify(self) -> bool | None: ...
    @property
    def rendering(self) -> bool | None: ...
    @property
    def items(self) -> list[RenderQueueItemProxy]: ...
    @property
    def typename(self) -> str | None: ...
    def get_item_by_index(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy | None: ...
    def getItemByIndex(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy | None: ...
    def add_composition(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def addComposition(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def queue_selected_compositions(self, *args: Any, **kwargs: Any) -> list[RenderQueueItemProxy]: ...
    def queueSelectedCompositions(self, *args: Any, **kwargs: Any) -> list[RenderQueueItemProxy]: ...
    def render(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def pause_rendering(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def pauseRendering(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def stop_rendering(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def stopRendering(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def show_window(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def showWindow(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def queue_in_a_m_e(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def queueInAME(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def set_queue_notify(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...
    def setQueueNotify(self, *args: Any, **kwargs: Any) -> RenderQueueProxy: ...


class RenderQueueItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def comp_id(self) -> Any: ...
    @property
    def compId(self) -> Any: ...
    @property
    def comp_name(self) -> str | None: ...
    @property
    def compName(self) -> str | None: ...
    @property
    def status(self) -> str | None: ...
    @property
    def elapsed_seconds(self) -> float | None: ...
    @property
    def elapsedSeconds(self) -> float | None: ...
    @property
    def render(self) -> bool | None: ...
    @property
    def skip_frames(self) -> int | None: ...
    @property
    def skipFrames(self) -> int | None: ...
    @property
    def queue_item_notify(self) -> bool | None: ...
    @property
    def queueItemNotify(self) -> bool | None: ...
    @property
    def time_span_start(self) -> float | None: ...
    @property
    def timeSpanStart(self) -> float | None: ...
    @property
    def time_span_duration(self) -> float | None: ...
    @property
    def timeSpanDuration(self) -> float | None: ...
    @property
    def num_output_modules(self) -> int | None: ...
    @property
    def numOutputModules(self) -> int | None: ...
    @property
    def templates(self) -> list[str]: ...
    @property
    def settings(self) -> dict[str, Any] | None: ...
    @property
    def output_modules(self) -> list[OutputModuleProxy]: ...
    @property
    def outputModules(self) -> list[OutputModuleProxy]: ...
    @property
    def typename(self) -> str | None: ...
    def output_module(self, *args: Any, **kwargs: Any) -> OutputModuleProxy | None: ...
    def outputModule(self, *args: Any, **kwargs: Any) -> OutputModuleProxy | None: ...
    def apply_template(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def applyTemplate(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def set_settings(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def setSettings(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def set_render(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def setRender(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def set_queue_item_notify(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...
    def setQueueItemNotify(self, *args: Any, **kwargs: Any) -> RenderQueueItemProxy: ...


class OutputModuleProxy:
    @property
    def item_index(self) -> int | None: ...
    @property
    def itemIndex(self) -> int | None: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def output_path(self) -> str | None: ...
    @property
    def outputPath(self) -> str | None: ...
    @property
    def include_source_xmp(self) -> bool | None: ...
    @property
    def includeSourceXmp(self) -> bool | None: ...
    @property
    def post_render_action(self) -> str | None: ...
    @property
    def postRenderAction(self) -> str | None: ...
    @property
    def templates(self) -> list[str]: ...
    @property
    def settings(self) -> dict[str, Any] | None: ...
    @property
    def typename(self) -> str | None: ...
    def apply_template(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def applyTemplate(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def set_settings(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def setSettings(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def set_output_path(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def setOutputPath(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def save_as_template(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
    def saveAsTemplate(self, *args: Any, **kwargs: Any) -> OutputModuleProxy: ...
