from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class InDesignSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class InDesign(InDesignSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_page(self) -> PageProxy | None: ...
    @property
    def activePage(self) -> PageProxy | None: ...
    @property
    def active_spread(self) -> SpreadProxy | None: ...
    @property
    def activeSpread(self) -> SpreadProxy | None: ...


class InDesignApp:
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_page(self) -> PageProxy | None: ...
    @property
    def activePage(self) -> PageProxy | None: ...
    @property
    def active_spread(self) -> SpreadProxy | None: ...
    @property
    def activeSpread(self) -> SpreadProxy | None: ...


class DocumentProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def page_count(self) -> int: ...
    @property
    def pageCount(self) -> int: ...
    @property
    def spread_count(self) -> int: ...
    @property
    def spreadCount(self) -> int: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def pages(self) -> list[PageProxy]: ...
    @property
    def spreads(self) -> list[SpreadProxy]: ...
    @property
    def active_page(self) -> PageProxy | None: ...
    @property
    def activePage(self) -> PageProxy | None: ...
    @property
    def active_spread(self) -> SpreadProxy | None: ...
    @property
    def activeSpread(self) -> SpreadProxy | None: ...
    def get_page(self, *args: Any, **kwargs: Any) -> PageProxy | None: ...
    def getPage(self, *args: Any, **kwargs: Any) -> PageProxy | None: ...
    def get_spread(self, *args: Any, **kwargs: Any) -> SpreadProxy | None: ...
    def getSpread(self, *args: Any, **kwargs: Any) -> SpreadProxy | None: ...


class PageProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def document_offset(self) -> Any: ...
    @property
    def documentOffset(self) -> Any: ...
    @property
    def side(self) -> Any: ...
    @property
    def bounds(self) -> list[Any]: ...
    @property
    def parent_id(self) -> int | str | None: ...
    @property
    def parentId(self) -> int | str | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def select(self, *args: Any, **kwargs: Any) -> PageProxy: ...


class SpreadProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def label(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def page_count(self) -> int: ...
    @property
    def pageCount(self) -> int: ...
    @property
    def page_names(self) -> list[str]: ...
    @property
    def pageNames(self) -> list[str]: ...
    @property
    def parent_id(self) -> int | str | None: ...
    @property
    def parentId(self) -> int | str | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
