from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class InDesignSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class InDesign(InDesignSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_page(self) -> PageProxy | None: ...
    @property
    def activePage(self) -> PageProxy | None: ...
    @property
    def active_spread(self) -> SpreadProxy | None: ...
    @property
    def activeSpread(self) -> SpreadProxy | None: ...
    @property
    def selected_text(self) -> TextSelectionProxy | None: ...
    @property
    def selectedText(self) -> TextSelectionProxy | None: ...


class InDesignApp:
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...
    @property
    def active_page(self) -> PageProxy | None: ...
    @property
    def activePage(self) -> PageProxy | None: ...
    @property
    def active_spread(self) -> SpreadProxy | None: ...
    @property
    def activeSpread(self) -> SpreadProxy | None: ...
    @property
    def selected_text(self) -> TextSelectionProxy | None: ...
    @property
    def selectedText(self) -> TextSelectionProxy | None: ...


class DocumentProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def page_count(self) -> int: ...
    @property
    def pageCount(self) -> int: ...
    @property
    def spread_count(self) -> int: ...
    @property
    def spreadCount(self) -> int: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def pages(self) -> list[PageProxy]: ...
    @property
    def spreads(self) -> list[SpreadProxy]: ...
    @property
    def text_frames(self) -> list[TextFrameProxy]: ...
    @property
    def textFrames(self) -> list[TextFrameProxy]: ...
    @property
    def stories(self) -> list[StoryProxy]: ...
    @property
    def paragraph_styles(self) -> list[ParagraphStyleProxy]: ...
    @property
    def paragraphStyles(self) -> list[ParagraphStyleProxy]: ...
    @property
    def character_styles(self) -> list[CharacterStyleProxy]: ...
    @property
    def characterStyles(self) -> list[CharacterStyleProxy]: ...
    @property
    def active_page(self) -> PageProxy | None: ...
    @property
    def activePage(self) -> PageProxy | None: ...
    @property
    def active_spread(self) -> SpreadProxy | None: ...
    @property
    def activeSpread(self) -> SpreadProxy | None: ...
    def get_page(self, *args: Any, **kwargs: Any) -> PageProxy | None: ...
    def getPage(self, *args: Any, **kwargs: Any) -> PageProxy | None: ...
    def get_spread(self, *args: Any, **kwargs: Any) -> SpreadProxy | None: ...
    def getSpread(self, *args: Any, **kwargs: Any) -> SpreadProxy | None: ...
    def get_text_frame(self, *args: Any, **kwargs: Any) -> TextFrameProxy | None: ...
    def getTextFrame(self, *args: Any, **kwargs: Any) -> TextFrameProxy | None: ...
    def get_story(self, *args: Any, **kwargs: Any) -> StoryProxy | None: ...
    def getStory(self, *args: Any, **kwargs: Any) -> StoryProxy | None: ...
    def get_paragraph_style(self, *args: Any, **kwargs: Any) -> ParagraphStyleProxy | None: ...
    def getParagraphStyle(self, *args: Any, **kwargs: Any) -> ParagraphStyleProxy | None: ...
    def get_character_style(self, *args: Any, **kwargs: Any) -> CharacterStyleProxy | None: ...
    def getCharacterStyle(self, *args: Any, **kwargs: Any) -> CharacterStyleProxy | None: ...


class TextSelectionProxy:
    @property
    def contents(self) -> str | None: ...
    @property
    def parent_story_id(self) -> int | str | None: ...
    @property
    def parentStoryId(self) -> int | str | None: ...
    @property
    def parent_story_name(self) -> str | None: ...
    @property
    def parentStoryName(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def length(self) -> Any: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class TextFrameProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def contents(self) -> str | None: ...
    @property
    def overflows(self) -> bool | None: ...
    @property
    def geometric_bounds(self) -> list[Any]: ...
    @property
    def geometricBounds(self) -> list[Any]: ...
    @property
    def parent_story_id(self) -> int | str | None: ...
    @property
    def parentStoryId(self) -> int | str | None: ...
    @property
    def parent_story_name(self) -> str | None: ...
    @property
    def parentStoryName(self) -> str | None: ...
    @property
    def parent_page_id(self) -> int | str | None: ...
    @property
    def parentPageId(self) -> int | str | None: ...
    @property
    def parent_page_name(self) -> str | None: ...
    @property
    def parentPageName(self) -> str | None: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def story(self) -> StoryProxy | None: ...
    def set_contents(self, *args: Any, **kwargs: Any) -> TextFrameProxy: ...
    def setContents(self, *args: Any, **kwargs: Any) -> TextFrameProxy: ...


class StoryProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def contents(self) -> str | None: ...
    @property
    def length(self) -> Any: ...
    @property
    def text_container_count(self) -> int: ...
    @property
    def textContainerCount(self) -> int: ...
    @property
    def paragraph_count(self) -> int: ...
    @property
    def paragraphCount(self) -> int: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def set_contents(self, *args: Any, **kwargs: Any) -> StoryProxy: ...
    def setContents(self, *args: Any, **kwargs: Any) -> StoryProxy: ...


class ParagraphStyleProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def applied_font(self) -> Any: ...
    @property
    def appliedFont(self) -> Any: ...
    @property
    def font_style(self) -> Any: ...
    @property
    def fontStyle(self) -> Any: ...
    @property
    def point_size(self) -> Any: ...
    @property
    def pointSize(self) -> Any: ...
    @property
    def leading(self) -> Any: ...
    @property
    def tracking(self) -> Any: ...
    @property
    def justification(self) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> ParagraphStyleProxy: ...


class CharacterStyleProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def applied_font(self) -> Any: ...
    @property
    def appliedFont(self) -> Any: ...
    @property
    def font_style(self) -> Any: ...
    @property
    def fontStyle(self) -> Any: ...
    @property
    def point_size(self) -> Any: ...
    @property
    def pointSize(self) -> Any: ...
    @property
    def leading(self) -> Any: ...
    @property
    def tracking(self) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> CharacterStyleProxy: ...


class PageProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def document_offset(self) -> Any: ...
    @property
    def documentOffset(self) -> Any: ...
    @property
    def side(self) -> Any: ...
    @property
    def bounds(self) -> list[Any]: ...
    @property
    def parent_id(self) -> int | str | None: ...
    @property
    def parentId(self) -> int | str | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def select(self, *args: Any, **kwargs: Any) -> PageProxy: ...


class SpreadProxy:
    @property
    def id(self) -> int | str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def label(self) -> str | None: ...
    @property
    def index(self) -> Any: ...
    @property
    def page_count(self) -> int: ...
    @property
    def pageCount(self) -> int: ...
    @property
    def page_names(self) -> list[str]: ...
    @property
    def pageNames(self) -> list[str]: ...
    @property
    def parent_id(self) -> int | str | None: ...
    @property
    def parentId(self) -> int | str | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def is_valid(self) -> bool | None: ...
    @property
    def isValid(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
