from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class PremiereSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class Premiere(PremiereSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_project(self) -> ProjectProxy | None: ...
    @property
    def activeProject(self) -> ProjectProxy | None: ...
    @property
    def project(self) -> ProjectProxy | None: ...
    @property
    def sequences(self) -> list[SequenceProxy]: ...
    @property
    def active_sequence(self) -> SequenceProxy | None: ...
    @property
    def activeSequence(self) -> SequenceProxy | None: ...
    @property
    def encoder(self) -> PremiereEncoder: ...
    @property
    def export(self) -> PremiereExport: ...


class PremiereApp:
    @property
    def version(self) -> str: ...
    @property
    def active_project(self) -> ProjectProxy | None: ...
    @property
    def activeProject(self) -> ProjectProxy | None: ...
    @property
    def project(self) -> ProjectProxy | None: ...
    @property
    def sequences(self) -> list[SequenceProxy]: ...
    @property
    def active_sequence(self) -> SequenceProxy | None: ...
    @property
    def activeSequence(self) -> SequenceProxy | None: ...
    @property
    def encoder(self) -> PremiereEncoder: ...
    @property
    def export(self) -> PremiereExport: ...


class ProjectProxy:
    @property
    def id(self) -> Any: ...
    @property
    def guid(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def item_count(self) -> int: ...
    @property
    def itemCount(self) -> int: ...
    @property
    def active_sequence(self) -> SequenceProxy | None: ...
    @property
    def activeSequence(self) -> SequenceProxy | None: ...
    @property
    def sequences(self) -> list[SequenceProxy]: ...
    @property
    def root_item(self) -> ProjectItemProxy | None: ...
    @property
    def rootItem(self) -> ProjectItemProxy | None: ...
    @property
    def selected_items(self) -> list[ProjectItemProxy]: ...
    @property
    def selectedItems(self) -> list[ProjectItemProxy]: ...
    def get_sequence(self, *args: Any, **kwargs: Any) -> SequenceProxy | None: ...
    def getSequence(self, *args: Any, **kwargs: Any) -> SequenceProxy | None: ...
    def import_files(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...
    def importFiles(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...


class ProjectItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> str | None: ...
    @property
    def type(self) -> Any: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def media_path(self) -> str | None: ...
    @property
    def mediaPath(self) -> str | None: ...
    @property
    def tree_path(self) -> str | None: ...
    @property
    def treePath(self) -> str | None: ...
    @property
    def parent_id(self) -> Any: ...
    @property
    def parentId(self) -> Any: ...
    @property
    def children(self) -> list[ProjectItemProxy]: ...
    @property
    def is_bin(self) -> bool: ...
    @property
    def isBin(self) -> bool: ...
    @property
    def is_clip(self) -> bool: ...
    @property
    def isClip(self) -> bool: ...
    @property
    def is_sequence(self) -> bool: ...
    @property
    def isSequence(self) -> bool: ...
    @property
    def can_proxy(self) -> bool | None: ...
    @property
    def canProxy(self) -> bool | None: ...
    @property
    def has_proxy(self) -> bool | None: ...
    @property
    def hasProxy(self) -> bool | None: ...
    @property
    def is_offline(self) -> bool | None: ...
    @property
    def isOffline(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def create_bin(self, *args: Any, **kwargs: Any) -> ProjectItemProxy: ...
    def createBin(self, *args: Any, **kwargs: Any) -> ProjectItemProxy: ...
    def find_items_matching_media_path(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...
    def findItemsMatchingMediaPath(self, *args: Any, **kwargs: Any) -> list[ProjectItemProxy]: ...
    def encode(self, *args: Any, **kwargs: Any) -> ExportJob: ...


class SequenceProxy:
    @property
    def id(self) -> Any: ...
    @property
    def sequence_id(self) -> Any: ...
    @property
    def sequenceId(self) -> Any: ...
    @property
    def name(self) -> str | None: ...
    @property
    def duration(self) -> Any: ...
    @property
    def timebase(self) -> Any: ...
    @property
    def typename(self) -> str | None: ...
    @property
    def video_tracks(self) -> list[TrackProxy]: ...
    @property
    def videoTracks(self) -> list[TrackProxy]: ...
    @property
    def audio_tracks(self) -> list[TrackProxy]: ...
    @property
    def audioTracks(self) -> list[TrackProxy]: ...
    @property
    def markers(self) -> list[MarkerProxy]: ...
    @property
    def selected_clips(self) -> list[ClipProxy]: ...
    @property
    def selectedClips(self) -> list[ClipProxy]: ...
    def create_marker(self, *args: Any, **kwargs: Any) -> MarkerProxy: ...
    def createMarker(self, *args: Any, **kwargs: Any) -> MarkerProxy: ...
    def export(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def export_frame(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def exportFrame(self, *args: Any, **kwargs: Any) -> ExportJob: ...


class TrackProxy:
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> str | None: ...
    @property
    def index(self) -> int | None: ...
    @property
    def media_type(self) -> str | None: ...
    @property
    def mediaType(self) -> str | None: ...
    @property
    def is_locked(self) -> bool | None: ...
    @property
    def isLocked(self) -> bool | None: ...
    @property
    def is_muted(self) -> bool | None: ...
    @property
    def isMuted(self) -> bool | None: ...
    @property
    def is_targeted(self) -> bool | None: ...
    @property
    def isTargeted(self) -> bool | None: ...
    @property
    def clips(self) -> list[ClipProxy]: ...
    @property
    def typename(self) -> str | None: ...


class ClipProxy:
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> str | None: ...
    @property
    def project_item_id(self) -> Any: ...
    @property
    def projectItemId(self) -> Any: ...
    @property
    def media_path(self) -> str | None: ...
    @property
    def mediaPath(self) -> str | None: ...
    @property
    def start(self) -> Any: ...
    @property
    def end(self) -> Any: ...
    @property
    def in_point(self) -> Any: ...
    @property
    def inPoint(self) -> Any: ...
    @property
    def out_point(self) -> Any: ...
    @property
    def outPoint(self) -> Any: ...
    @property
    def duration(self) -> Any: ...
    @property
    def is_enabled(self) -> bool | None: ...
    @property
    def isEnabled(self) -> bool | None: ...
    @property
    def is_selected(self) -> bool | None: ...
    @property
    def isSelected(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class MarkerProxy:
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> str | None: ...
    @property
    def comments(self) -> str | None: ...
    @property
    def start(self) -> Any: ...
    @property
    def end(self) -> Any: ...
    @property
    def duration(self) -> Any: ...
    @property
    def marker_type(self) -> str | None: ...
    @property
    def markerType(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...


class PremiereEncoder:
    @property
    def presets(self) -> list[EncoderPreset]: ...
    @property
    def is_ame_installed(self) -> bool | None: ...
    @property
    def isAmeInstalled(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
    def get_presets(self, *args: Any, **kwargs: Any) -> list[EncoderPreset]: ...
    def getPresets(self, *args: Any, **kwargs: Any) -> list[EncoderPreset]: ...
    def get_export_file_extension(self, *args: Any, **kwargs: Any) -> str: ...
    def getExportFileExtension(self, *args: Any, **kwargs: Any) -> str: ...
    def encode_file(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def encodeFile(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def encode_project_item(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def encodeProjectItem(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def export_sequence(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def exportSequence(self, *args: Any, **kwargs: Any) -> ExportJob: ...


class PremiereExport:
    def export_frame(self, *args: Any, **kwargs: Any) -> ExportJob: ...
    def exportFrame(self, *args: Any, **kwargs: Any) -> ExportJob: ...


class EncoderPreset:
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def format(self) -> str | None: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...


class ExportJob:
    @property
    def id(self) -> Any: ...
    @property
    def job_id(self) -> Any: ...
    @property
    def jobId(self) -> Any: ...
    @property
    def status(self) -> str | None: ...
    @property
    def output_path(self) -> str | None: ...
    @property
    def outputPath(self) -> str | None: ...
    @property
    def preset_path(self) -> str | None: ...
    @property
    def presetPath(self) -> str | None: ...
    @property
    def source_id(self) -> Any: ...
    @property
    def sourceId(self) -> Any: ...
    @property
    def source_name(self) -> str | None: ...
    @property
    def sourceName(self) -> str | None: ...
    @property
    def export_type(self) -> str | None: ...
    @property
    def exportType(self) -> str | None: ...
    @property
    def remove_on_completion(self) -> bool | None: ...
    @property
    def removeOnCompletion(self) -> bool | None: ...
    @property
    def started(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...
