from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class IllustratorSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class Illustrator(IllustratorSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...


class IllustratorApp:
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...


class DocumentProxy:
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
