from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class IllustratorSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class Illustrator(IllustratorSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...


class IllustratorApp:
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...


class DocumentProxy:
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def artboard_count(self) -> int | None: ...
    @property
    def artboardCount(self) -> int | None: ...
    @property
    def layer_count(self) -> int | None: ...
    @property
    def layerCount(self) -> int | None: ...
    @property
    def page_item_count(self) -> int | None: ...
    @property
    def pageItemCount(self) -> int | None: ...
    @property
    def selection_count(self) -> int | None: ...
    @property
    def selectionCount(self) -> int | None: ...
    @property
    def artboards(self) -> list[ArtboardProxy]: ...
    @property
    def active_artboard(self) -> ArtboardProxy | None: ...
    @property
    def activeArtboard(self) -> ArtboardProxy | None: ...
    @property
    def active_artboard_index(self) -> int | None: ...
    @property
    def activeArtboardIndex(self) -> int | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def page_items(self) -> list[PageItemProxy]: ...
    @property
    def pageItems(self) -> list[PageItemProxy]: ...
    @property
    def selection(self) -> list[PageItemProxy]: ...
    @property
    def typename(self) -> str | None: ...
    def get_layer_by_name(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def getLayerByName(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def get_page_item_by_name(self, *args: Any, **kwargs: Any) -> PageItemProxy | None: ...
    def getPageItemByName(self, *args: Any, **kwargs: Any) -> PageItemProxy | None: ...


class ArtboardProxy:
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def artboard_rect(self) -> Any: ...
    @property
    def artboardRect(self) -> Any: ...
    @property
    def ruler_origin(self) -> Any: ...
    @property
    def rulerOrigin(self) -> Any: ...
    @property
    def ruler_par(self) -> Any: ...
    @property
    def rulerPar(self) -> Any: ...
    @property
    def show_center(self) -> bool | None: ...
    @property
    def showCenter(self) -> bool | None: ...
    @property
    def show_cross_hairs(self) -> bool | None: ...
    @property
    def showCrossHairs(self) -> bool | None: ...
    @property
    def show_safe_areas(self) -> bool | None: ...
    @property
    def showSafeAreas(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class LayerProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def visible(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def printable(self) -> bool | None: ...
    @property
    def preview(self) -> bool | None: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def has_selected_artwork(self) -> bool | None: ...
    @property
    def hasSelectedArtwork(self) -> bool | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_count(self) -> int | None: ...
    @property
    def layerCount(self) -> int | None: ...
    @property
    def page_item_count(self) -> int | None: ...
    @property
    def pageItemCount(self) -> int | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def page_items(self) -> list[PageItemProxy]: ...
    @property
    def pageItems(self) -> list[PageItemProxy]: ...
    @property
    def typename(self) -> str | None: ...


class PageItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def editable(self) -> bool | None: ...
    @property
    def sliced(self) -> bool | None: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def control_bounds(self) -> Any: ...
    @property
    def controlBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def note(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...
