from __future__ import annotations

from typing import Any
from adobe.core import BrokerClient
from adobe.core.session import HostSession

class IllustratorSession(HostSession):
    def __init__(self, client: BrokerClient | None = ...) -> None: ...


class Illustrator(IllustratorSession):
    def __init__(self, *, broker_url: str | None = ..., token: str | None = ..., target: str = "default", timeout: float = ..., client: BrokerClient | None = ...) -> None: ...
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...


class IllustratorApp:
    @property
    def version(self) -> str: ...
    @property
    def active_document(self) -> DocumentProxy | None: ...
    @property
    def activeDocument(self) -> DocumentProxy | None: ...


class DocumentProxy:
    @property
    def name(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def artboard_count(self) -> int | None: ...
    @property
    def artboardCount(self) -> int | None: ...
    @property
    def layer_count(self) -> int | None: ...
    @property
    def layerCount(self) -> int | None: ...
    @property
    def page_item_count(self) -> int | None: ...
    @property
    def pageItemCount(self) -> int | None: ...
    @property
    def path_item_count(self) -> int | None: ...
    @property
    def pathItemCount(self) -> int | None: ...
    @property
    def compound_path_item_count(self) -> int | None: ...
    @property
    def compoundPathItemCount(self) -> int | None: ...
    @property
    def placed_item_count(self) -> int | None: ...
    @property
    def placedItemCount(self) -> int | None: ...
    @property
    def raster_item_count(self) -> int | None: ...
    @property
    def rasterItemCount(self) -> int | None: ...
    @property
    def text_frame_count(self) -> int | None: ...
    @property
    def textFrameCount(self) -> int | None: ...
    @property
    def story_count(self) -> int | None: ...
    @property
    def storyCount(self) -> int | None: ...
    @property
    def swatch_count(self) -> int | None: ...
    @property
    def swatchCount(self) -> int | None: ...
    @property
    def selection_count(self) -> int | None: ...
    @property
    def selectionCount(self) -> int | None: ...
    @property
    def artboards(self) -> list[ArtboardProxy]: ...
    @property
    def active_artboard(self) -> ArtboardProxy | None: ...
    @property
    def activeArtboard(self) -> ArtboardProxy | None: ...
    @property
    def active_artboard_index(self) -> int | None: ...
    @property
    def activeArtboardIndex(self) -> int | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def page_items(self) -> list[PageItemProxy]: ...
    @property
    def pageItems(self) -> list[PageItemProxy]: ...
    @property
    def selection(self) -> list[PageItemProxy]: ...
    @property
    def path_items(self) -> list[PathItemProxy]: ...
    @property
    def pathItems(self) -> list[PathItemProxy]: ...
    @property
    def selected_path_items(self) -> list[PathItemProxy]: ...
    @property
    def selectedPathItems(self) -> list[PathItemProxy]: ...
    @property
    def compound_path_items(self) -> list[CompoundPathItemProxy]: ...
    @property
    def compoundPathItems(self) -> list[CompoundPathItemProxy]: ...
    @property
    def selected_compound_path_items(self) -> list[CompoundPathItemProxy]: ...
    @property
    def selectedCompoundPathItems(self) -> list[CompoundPathItemProxy]: ...
    @property
    def placed_items(self) -> list[PlacedItemProxy]: ...
    @property
    def placedItems(self) -> list[PlacedItemProxy]: ...
    @property
    def selected_placed_items(self) -> list[PlacedItemProxy]: ...
    @property
    def selectedPlacedItems(self) -> list[PlacedItemProxy]: ...
    @property
    def raster_items(self) -> list[RasterItemProxy]: ...
    @property
    def rasterItems(self) -> list[RasterItemProxy]: ...
    @property
    def selected_raster_items(self) -> list[RasterItemProxy]: ...
    @property
    def selectedRasterItems(self) -> list[RasterItemProxy]: ...
    @property
    def text_frames(self) -> list[TextFrameProxy]: ...
    @property
    def textFrames(self) -> list[TextFrameProxy]: ...
    @property
    def selected_text_frames(self) -> list[TextFrameProxy]: ...
    @property
    def selectedTextFrames(self) -> list[TextFrameProxy]: ...
    @property
    def stories(self) -> list[StoryProxy]: ...
    @property
    def swatches(self) -> list[SwatchProxy]: ...
    @property
    def exports(self) -> DocumentExportProxy: ...
    @property
    def typename(self) -> str | None: ...
    def get_layer_by_name(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def getLayerByName(self, *args: Any, **kwargs: Any) -> LayerProxy | None: ...
    def get_page_item_by_name(self, *args: Any, **kwargs: Any) -> PageItemProxy | None: ...
    def getPageItemByName(self, *args: Any, **kwargs: Any) -> PageItemProxy | None: ...
    def get_path_item_by_name(self, *args: Any, **kwargs: Any) -> PathItemProxy | None: ...
    def getPathItemByName(self, *args: Any, **kwargs: Any) -> PathItemProxy | None: ...
    def get_compound_path_item_by_name(self, *args: Any, **kwargs: Any) -> CompoundPathItemProxy | None: ...
    def getCompoundPathItemByName(self, *args: Any, **kwargs: Any) -> CompoundPathItemProxy | None: ...
    def get_placed_item_by_name(self, *args: Any, **kwargs: Any) -> PlacedItemProxy | None: ...
    def getPlacedItemByName(self, *args: Any, **kwargs: Any) -> PlacedItemProxy | None: ...
    def get_raster_item_by_name(self, *args: Any, **kwargs: Any) -> RasterItemProxy | None: ...
    def getRasterItemByName(self, *args: Any, **kwargs: Any) -> RasterItemProxy | None: ...
    def get_text_frame_by_name(self, *args: Any, **kwargs: Any) -> TextFrameProxy | None: ...
    def getTextFrameByName(self, *args: Any, **kwargs: Any) -> TextFrameProxy | None: ...
    def get_story_by_name(self, *args: Any, **kwargs: Any) -> StoryProxy | None: ...
    def getStoryByName(self, *args: Any, **kwargs: Any) -> StoryProxy | None: ...
    def get_swatch_by_name(self, *args: Any, **kwargs: Any) -> SwatchProxy | None: ...
    def getSwatchByName(self, *args: Any, **kwargs: Any) -> SwatchProxy | None: ...
    def save(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def save_as(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def saveAs(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def export_file(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def exportFile(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...


class ArtboardProxy:
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def artboard_rect(self) -> Any: ...
    @property
    def artboardRect(self) -> Any: ...
    @property
    def ruler_origin(self) -> Any: ...
    @property
    def rulerOrigin(self) -> Any: ...
    @property
    def ruler_par(self) -> Any: ...
    @property
    def rulerPar(self) -> Any: ...
    @property
    def show_center(self) -> bool | None: ...
    @property
    def showCenter(self) -> bool | None: ...
    @property
    def show_cross_hairs(self) -> bool | None: ...
    @property
    def showCrossHairs(self) -> bool | None: ...
    @property
    def show_safe_areas(self) -> bool | None: ...
    @property
    def showSafeAreas(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class LayerProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def visible(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def printable(self) -> bool | None: ...
    @property
    def preview(self) -> bool | None: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def has_selected_artwork(self) -> bool | None: ...
    @property
    def hasSelectedArtwork(self) -> bool | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_count(self) -> int | None: ...
    @property
    def layerCount(self) -> int | None: ...
    @property
    def page_item_count(self) -> int | None: ...
    @property
    def pageItemCount(self) -> int | None: ...
    @property
    def layers(self) -> list[LayerProxy]: ...
    @property
    def page_items(self) -> list[PageItemProxy]: ...
    @property
    def pageItems(self) -> list[PageItemProxy]: ...
    @property
    def path_items(self) -> list[PathItemProxy]: ...
    @property
    def pathItems(self) -> list[PathItemProxy]: ...
    @property
    def compound_path_items(self) -> list[CompoundPathItemProxy]: ...
    @property
    def compoundPathItems(self) -> list[CompoundPathItemProxy]: ...
    @property
    def placed_items(self) -> list[PlacedItemProxy]: ...
    @property
    def placedItems(self) -> list[PlacedItemProxy]: ...
    @property
    def raster_items(self) -> list[RasterItemProxy]: ...
    @property
    def rasterItems(self) -> list[RasterItemProxy]: ...
    @property
    def typename(self) -> str | None: ...


class PageItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def editable(self) -> bool | None: ...
    @property
    def sliced(self) -> bool | None: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def control_bounds(self) -> Any: ...
    @property
    def controlBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def note(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...


class PathItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def editable(self) -> bool | None: ...
    @property
    def sliced(self) -> bool | None: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def control_bounds(self) -> Any: ...
    @property
    def controlBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def note(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def area(self) -> float | None: ...
    @property
    def closed(self) -> bool | None: ...
    @property
    def clipping(self) -> bool | None: ...
    @property
    def evenodd(self) -> bool | None: ...
    @property
    def filled(self) -> bool | None: ...
    @property
    def fill_color(self) -> Any: ...
    @property
    def fillColor(self) -> Any: ...
    @property
    def fill_overprint(self) -> bool | None: ...
    @property
    def fillOverprint(self) -> bool | None: ...
    @property
    def stroked(self) -> bool | None: ...
    @property
    def stroke_color(self) -> Any: ...
    @property
    def strokeColor(self) -> Any: ...
    @property
    def stroke_width(self) -> float | None: ...
    @property
    def strokeWidth(self) -> float | None: ...
    @property
    def stroke_cap(self) -> Any: ...
    @property
    def strokeCap(self) -> Any: ...
    @property
    def stroke_join(self) -> Any: ...
    @property
    def strokeJoin(self) -> Any: ...
    @property
    def stroke_dashes(self) -> Any: ...
    @property
    def strokeDashes(self) -> Any: ...
    @property
    def stroke_dash_offset(self) -> float | None: ...
    @property
    def strokeDashOffset(self) -> float | None: ...
    @property
    def stroke_miter_limit(self) -> float | None: ...
    @property
    def strokeMiterLimit(self) -> float | None: ...
    @property
    def stroke_overprint(self) -> bool | None: ...
    @property
    def strokeOverprint(self) -> bool | None: ...
    @property
    def guides(self) -> bool | None: ...
    @property
    def length(self) -> float | None: ...
    @property
    def path_point_count(self) -> int | None: ...
    @property
    def pathPointCount(self) -> int | None: ...
    @property
    def selected_path_point_count(self) -> int | None: ...
    @property
    def selectedPathPointCount(self) -> int | None: ...
    @property
    def pixel_aligned(self) -> bool | None: ...
    @property
    def pixelAligned(self) -> bool | None: ...
    @property
    def polarity(self) -> Any: ...
    @property
    def typename(self) -> str | None: ...
    def set_entire_path(self, *args: Any, **kwargs: Any) -> Any: ...
    def setEntirePath(self, *args: Any, **kwargs: Any) -> Any: ...
    def translate(self, *args: Any, **kwargs: Any) -> Any: ...
    def resize(self, *args: Any, **kwargs: Any) -> Any: ...
    def rotate(self, *args: Any, **kwargs: Any) -> Any: ...


class CompoundPathItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def editable(self) -> bool | None: ...
    @property
    def sliced(self) -> bool | None: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def control_bounds(self) -> Any: ...
    @property
    def controlBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def note(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def path_item_count(self) -> int | None: ...
    @property
    def pathItemCount(self) -> int | None: ...
    @property
    def path_items(self) -> list[PathItemProxy]: ...
    @property
    def pathItems(self) -> list[PathItemProxy]: ...
    @property
    def typename(self) -> str | None: ...


class PlacedItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def editable(self) -> bool | None: ...
    @property
    def sliced(self) -> bool | None: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def control_bounds(self) -> Any: ...
    @property
    def controlBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def note(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def fileName(self) -> str | None: ...
    @property
    def bounding_box(self) -> Any: ...
    @property
    def boundingBox(self) -> Any: ...
    @property
    def matrix(self) -> Any: ...
    @property
    def typename(self) -> str | None: ...


class RasterItemProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def item_type(self) -> str | None: ...
    @property
    def itemType(self) -> str | None: ...
    @property
    def hidden(self) -> bool | None: ...
    @property
    def locked(self) -> bool | None: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def editable(self) -> bool | None: ...
    @property
    def sliced(self) -> bool | None: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def control_bounds(self) -> Any: ...
    @property
    def controlBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def opacity(self) -> float | None: ...
    @property
    def parent_name(self) -> str | None: ...
    @property
    def parentName(self) -> str | None: ...
    @property
    def parent_typename(self) -> str | None: ...
    @property
    def parentTypename(self) -> str | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def note(self) -> str | None: ...
    @property
    def url(self) -> str | None: ...
    @property
    def file_path(self) -> str | None: ...
    @property
    def filePath(self) -> str | None: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def fileName(self) -> str | None: ...
    @property
    def bounding_box(self) -> Any: ...
    @property
    def boundingBox(self) -> Any: ...
    @property
    def matrix(self) -> Any: ...
    @property
    def embedded(self) -> bool | None: ...
    @property
    def bits_per_channel(self) -> int | None: ...
    @property
    def bitsPerChannel(self) -> int | None: ...
    @property
    def channels(self) -> int | None: ...
    @property
    def colorants(self) -> Any: ...
    @property
    def colorized_grayscale(self) -> bool | None: ...
    @property
    def colorizedGrayscale(self) -> bool | None: ...
    @property
    def image_color_space(self) -> Any: ...
    @property
    def imageColorSpace(self) -> Any: ...
    @property
    def overprint(self) -> bool | None: ...
    @property
    def typename(self) -> str | None: ...


class TextFrameProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def contents(self) -> str | None: ...
    @property
    def kind(self) -> Any: ...
    @property
    def orientation(self) -> Any: ...
    @property
    def position(self) -> Any: ...
    @property
    def geometric_bounds(self) -> Any: ...
    @property
    def geometricBounds(self) -> Any: ...
    @property
    def visible_bounds(self) -> Any: ...
    @property
    def visibleBounds(self) -> Any: ...
    @property
    def width(self) -> Any: ...
    @property
    def height(self) -> Any: ...
    @property
    def selected(self) -> bool | None: ...
    @property
    def layer_name(self) -> str | None: ...
    @property
    def layerName(self) -> str | None: ...
    @property
    def character_count(self) -> int | None: ...
    @property
    def characterCount(self) -> int | None: ...
    @property
    def word_count(self) -> int | None: ...
    @property
    def wordCount(self) -> int | None: ...
    @property
    def paragraph_count(self) -> int | None: ...
    @property
    def paragraphCount(self) -> int | None: ...
    @property
    def typename(self) -> str | None: ...
    def set_contents(self, *args: Any, **kwargs: Any) -> TextFrameProxy: ...
    def setContents(self, *args: Any, **kwargs: Any) -> TextFrameProxy: ...


class StoryProxy:
    @property
    def id(self) -> Any: ...
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def contents(self) -> str | None: ...
    @property
    def length(self) -> int | None: ...
    @property
    def text_frame_count(self) -> int | None: ...
    @property
    def textFrameCount(self) -> int | None: ...
    @property
    def word_count(self) -> int | None: ...
    @property
    def wordCount(self) -> int | None: ...
    @property
    def paragraph_count(self) -> int | None: ...
    @property
    def paragraphCount(self) -> int | None: ...
    @property
    def typename(self) -> str | None: ...


class SwatchProxy:
    @property
    def index(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def color(self) -> Any: ...
    @property
    def color_typename(self) -> str | None: ...
    @property
    def colorTypename(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...


class DocumentExportProxy:
    def file(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def png24(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def jpeg(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def svg(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...
    def pdf(self, *args: Any, **kwargs: Any) -> ExportResultProxy: ...


class ExportResultProxy:
    @property
    def ok(self) -> bool | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def format(self) -> str | None: ...
    @property
    def preset(self) -> str | None: ...
    @property
    def options(self) -> dict[str, Any]: ...
    @property
    def document_name(self) -> str | None: ...
    @property
    def documentName(self) -> str | None: ...
    @property
    def typename(self) -> str | None: ...
